server:
  port: 8383
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: DOCTOR-SERVICE
          uri: lb://DOCTOR-SERVICE
          predicates:
          - Path=/doctors/**
        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
          - Path=/patients/**
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost